var $header = $('header');
var $h1 = $('h1');
var $main = $('main');
var $h2 = $('h2');
var $images = $('img');
var $dl = $('dl');
var $dt = $('dt');
var $li = $('li');
var $mainlist = $('main ul');

$header.addClass('masthead');
$h1.removeClass('big-heading').addClass('logo');
$main.addClass('wrapper');
$('main p:first-child').addClass('intro');
$h2.addClass('slug-head');
$mainlist.addClass('slug-list');
$images.addClass('slug-img');
$('ul li:first-child').addClass('slug-list-first');
$('uil li:last-child').addClass('slug-list-last');
$dl.addClass('classification');
$dt.removeClass('big-label');
$('ul li:last-child').show();
